import Footer from '@/components/Footer'
import MortgageCalculator from '@/components/MortgageCalculator'
import Navbar from '@/components/Navbar'
import Link from 'next/link'

export const metadata = {
  title: 'Mortgage Calculator | NJV Accountants',
  description: 'Estimate mortgage repayments, interest, and housing costs with NJV Accountants’ mortgage calculator.',
}

export default function MortgageCalculatorPage() {
  return <><Navbar /><main><section className="bg-navy pt-[70px]"><div className="mx-auto max-w-site px-6 py-16"><Link href="/calculators" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-gold/70 no-underline transition-colors hover:text-gold">← All Calculators</Link><div className="mb-5 flex items-center gap-3.5 text-xs font-semibold tracking-[.12em] uppercase text-gold"><span className="block h-[22px] w-[3px] shrink-0 bg-gold" />Home finance tool</div><h1 className="font-display text-[clamp(2.25rem,5vw,3.25rem)] font-bold leading-tight text-white">Mortgage <em className="not-italic text-gold">Calculator</em></h1><p className="mt-5 max-w-[620px] text-[1.0625rem] leading-[1.75] text-white/65">Estimate your mortgage payment, total interest, and the full monthly cost of owning a home. Adjust the loan, rate, and property costs to plan with confidence.</p></div></section><section className="bg-cream py-16"><div className="mx-auto max-w-site px-6"><MortgageCalculator /></div></section><section className="bg-white py-16"><div className="mx-auto max-w-site px-6"><div className="max-w-3xl"><p className="text-xs font-semibold tracking-[.12em] uppercase text-gold">A practical guide</p><h2 className="mt-4 font-display text-3xl font-bold text-navy">Understanding your mortgage estimate</h2><p className="mt-4 leading-relaxed text-slate">A repayment mortgage pays down both the original loan and the interest over the selected term. A larger down payment reduces the amount borrowed, which can lower the regular payment and the interest paid over time.</p><p className="mt-4 leading-relaxed text-slate">Interest-only mortgages cover interest during the term and leave the original balance outstanding. Adjustable-rate mortgages can change after their initial period, so use the adjustment fields to see how a later rate may affect payments.</p><p className="mt-4 leading-relaxed text-slate">The amortization schedule shows how each payment is split between principal, interest, and estimated escrow costs. This calculator is an estimate for planning only; lender rates, fees, eligibility, and final payments may differ.</p></div></div></section><section className="bg-gold py-16"><div className="mx-auto flex max-w-site flex-wrap items-center justify-between gap-8 px-6"><div><h2 className="font-display text-2xl font-bold text-navy">Need help planning your finances?</h2><p className="mt-2 text-sm text-navy/70">Our advisers can help you make informed financial decisions.</p></div><Link href="/#contact" className="shrink-0 rounded-sm bg-navy px-8 py-3.5 text-sm font-semibold tracking-[.05em] text-white uppercase no-underline transition-colors hover:bg-navy-light">Speak to a Partner ›</Link></div></section></main><Footer /></>
}
