'use client'

import { useMemo, useState } from 'react'
import CalculatorActions from '@/components/CalculatorActions'
import ResultBarChart from '@/components/ResultBarChart'
import { calculateSalaryPaycheck, type PayFrequency, type SalaryPaycheckInput } from '@/lib/salaryPaycheck'
import type { FilingStatus } from '@/lib/federalTax'
import { formatCurrency } from '@/lib/formatters'

const states = ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming']
const statuses: Record<FilingStatus,string> = { single:'Single', marriedJoint:'Married filing jointly', marriedSeparate:'Married filing separately', headOfHousehold:'Head of household' }
const frequencies: Record<PayFrequency,string> = { weekly:'Weekly', biweekly:'Every two weeks', semimonthly:'Twice a month', monthly:'Monthly' }
const initial: SalaryPaycheckInput = { annualSalary:75000, bonus:0, commission:0, overtime:0, frequency:'biweekly', filingStatus:'single', dependants:0, preTaxDeductions:0, postTaxDeductions:0, stateRate:0, includeSocialSecurity:true, includeMedicare:true }
const usd = (value:number) => formatCurrency(value, 'USD')

export default function SalaryPaycheckCalculator() {
 const [input,setInput]=useState(initial); const [state,setState]=useState('');
 const result=useMemo(()=>calculateSalaryPaycheck(input),[input]);
 const setNum=(key: keyof Pick<SalaryPaycheckInput,'annualSalary'|'bonus'|'commission'|'overtime'|'dependants'|'preTaxDeductions'|'postTaxDeductions'|'stateRate'>, value:string)=>setInput(i=>({...i,[key]:Math.max(0,Number(value)||0)}));
 const rows=[['Salary Paycheck Estimate','Per paycheck','Annual'],['Gross pay',result.grossPerPaycheck,result.annualGross],['Pre-tax deductions',result.preTaxPerPaycheck,result.preTaxPerPaycheck*result.payPeriods],['Federal income tax',result.federalPerPaycheck,result.annualFederal],['Social Security',result.socialSecurityPerPaycheck,result.annualSocialSecurity],['Medicare',result.medicarePerPaycheck,result.annualMedicare],['State/local estimate',result.stateEstimatePerPaycheck,result.annualStateEstimate],['Post-tax deductions',result.postTaxPerPaycheck,result.postTaxPerPaycheck*result.payPeriods],['Net pay',result.netPerPaycheck,result.annualNet]];
 return <div className="grid grid-cols-1 gap-8 lg:grid-cols-2">
  <section className="bg-white border border-border rounded-sm p-7 md:p-8 shadow-sm"><h2 className="font-display text-2xl font-bold text-navy">Paycheck details</h2><p className="mt-2 text-sm text-slate">Enter annual earnings and deductions in U.S. dollars. State and local withholding is an estimate you control.</p>
   <div className="mt-7 grid gap-5 sm:grid-cols-2"><Select label="Pay frequency" value={input.frequency} onChange={v=>setInput(i=>({...i,frequency:v as PayFrequency}))} options={frequencies}/><Select label="Filing status" value={input.filingStatus} onChange={v=>setInput(i=>({...i,filingStatus:v as FilingStatus}))} options={statuses}/><Number label="Annual salary" value={input.annualSalary} onChange={v=>setNum('annualSalary',v)}/><Number label="Dependants" value={input.dependants} prefix="" onChange={v=>setNum('dependants',v)}/><Number label="Annual bonus" value={input.bonus} onChange={v=>setNum('bonus',v)}/><Number label="Annual commission" value={input.commission} onChange={v=>setNum('commission',v)}/><Number label="Annual overtime" value={input.overtime} onChange={v=>setNum('overtime',v)}/><Number label="Pre-tax deductions / paycheck" value={input.preTaxDeductions} onChange={v=>setNum('preTaxDeductions',v)}/><Number label="Post-tax deductions / paycheck" value={input.postTaxDeductions} onChange={v=>setNum('postTaxDeductions',v)}/><label className="block"><span className="block text-xs font-semibold tracking-[.08em] uppercase text-slate mb-2">State</span><select value={state} onChange={e=>setState(e.target.value)} className="w-full bg-cream border border-border rounded-sm px-4 py-3 text-navy"><option value="">Select state (optional)</option>{states.map(s=><option key={s}>{s}</option>)}</select></label><Number label="State/local estimate rate" value={input.stateRate*100} suffix="%" onChange={v=>setNum('stateRate',String((Number(v)||0)/100))}/></div>
   <div className="mt-6 flex flex-wrap gap-5 border-t border-border pt-5"><Toggle label="Social Security (6.2%)" checked={input.includeSocialSecurity} onChange={v=>setInput(i=>({...i,includeSocialSecurity:v}))}/><Toggle label="Medicare (1.45%)" checked={input.includeMedicare} onChange={v=>setInput(i=>({...i,includeMedicare:v}))}/></div>
  </section>
  <section className="bg-navy rounded-sm p-7 md:p-8 text-white relative overflow-hidden"><div className="hero-pattern"/><div className="relative"><div className="flex gap-3 text-xs font-semibold tracking-[.12em] uppercase text-gold"><span className="w-[3px] h-[18px] bg-gold"/>Paycheck estimate</div><h2 className="font-display text-2xl font-bold mt-4">Your take-home pay</h2><div className="mt-7"><p className="text-xs uppercase tracking-[.08em] text-white/50">Net pay / {frequencies[input.frequency]}</p><p className="font-display text-4xl text-gold font-bold mt-1">{usd(result.netPerPaycheck)}</p><p className="text-sm text-white/60 mt-2">{usd(result.annualNet)} estimated annual net pay</p></div><div className="grid grid-cols-2 gap-px bg-white/10 mt-7"><Stat label="Gross pay" value={usd(result.grossPerPaycheck)}/><Stat label="Federal tax" value={usd(result.federalPerPaycheck)}/><Stat label="FICA + Medicare" value={usd(result.socialSecurityPerPaycheck+result.medicarePerPaycheck)}/><Stat label={state ? `${state} estimate`:'State/local estimate'} value={usd(result.stateEstimatePerPaycheck)}/></div><p className="mt-6 text-xs leading-relaxed text-white/55">Federal withholding and FICA are estimates based on your entries. State and local tax rates vary by jurisdiction.</p></div></section>
  <section className="lg:col-span-2 bg-white border border-border rounded-sm p-7 md:p-8"><div className="grid gap-10 lg:grid-cols-2"><ResultBarChart title="Estimated deductions per paycheck" items={[['Federal income tax',result.federalPerPaycheck],['Social Security',result.socialSecurityPerPaycheck],['Medicare',result.medicarePerPaycheck],['State/local estimate',result.stateEstimatePerPaycheck],['Post-tax deductions',result.postTaxPerPaycheck]].map(([name,value])=>({name:name as string,value:value as number,formattedValue:usd(value as number)}))}/><div><h3 className="font-display text-xl font-bold text-navy">Paycheck breakdown</h3><div className="overflow-x-auto mt-4 border border-border rounded-sm"><table className="w-full min-w-[460px] text-sm"><thead className="bg-cream text-navy"><tr><th className="text-left px-4 py-3">Item</th><th className="text-right px-4 py-3">Per paycheck</th><th className="text-right px-4 py-3">Annual</th></tr></thead><tbody>{rows.slice(1).map(r=><tr key={r[0] as string} className="border-t border-border"><td className="px-4 py-3 text-slate">{r[0]}</td><td className="px-4 py-3 text-right text-slate">{usd(r[1] as number)}</td><td className="px-4 py-3 text-right font-semibold text-navy">{usd(r[2] as number)}</td></tr>)}</tbody></table></div><div className="mt-6"><CalculatorActions filename="salary-paycheck-estimate.csv" rows={rows} shareTitle="Salary paycheck estimate"/></div></div></div></section>
 </div>
}
function Number({label,value,onChange,prefix='$',suffix}:{label:string;value:number;onChange:(v:string)=>void;prefix?:string;suffix?:string}){return <label className="block"><span className="block text-xs font-semibold tracking-[.08em] uppercase text-slate mb-2">{label}</span><div className="relative">{prefix&&<span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate">{prefix}</span>}<input type="number" min="0" value={value} onChange={e=>onChange(e.target.value)} className={`w-full bg-cream border border-border rounded-sm py-3 text-navy ${prefix?'pl-8 pr-4':suffix?'pl-4 pr-9':'px-4'}`}/>{suffix&&<span className="absolute right-4 top-1/2 -translate-y-1/2 text-slate">{suffix}</span>}</div></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="block"><span className="block text-xs font-semibold tracking-[.08em] uppercase text-slate mb-2">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full bg-cream border border-border rounded-sm px-4 py-3 text-navy">{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-sm text-navy cursor-pointer"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-gold"/>{label}</label>}
function Stat({label,value}:{label:string;value:string}){return <div className="bg-navy p-4"><p className="text-[.65rem] uppercase tracking-[.08em] text-white/45">{label}</p><p className="font-semibold mt-1">{value}</p></div>}
