import type { Metadata } from 'next'
import Link from 'next/link'
import FederalTaxCalculator from '@/components/FederalTaxCalculator'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { FEDERAL_TAX_RULES_2026, type FilingStatus } from '@/lib/federalTax'

export const metadata: Metadata = {
  title: 'Federal Income Tax Calculator 2026 | NJV Accountants',
  description: 'Estimate your 2026 U.S. federal income tax, marginal rate, state and local tax estimate, and expected refund or balance due.',
}

const statusLabels: Record<FilingStatus, string> = { single: 'Single', marriedSeparate: 'Married filing separately', marriedJoint: 'Married filing jointly', headOfHousehold: 'Head of household' }
const rates = [10, 12, 22, 24, 32, 35, 37]
const money = (amount: number) => `$${amount.toLocaleString('en-US')}`

export default function FederalTaxPage() {
  return <><Navbar /><main>
    <section className="pt-[70px] bg-navy"><div className="max-w-site mx-auto px-6 py-16"><a href="/calculators" className="inline-flex items-center gap-2 text-gold/70 text-sm font-semibold mb-8 hover:text-gold transition-colors no-underline">← All Calculators</a><div className="flex items-center gap-3.5 text-xs font-semibold tracking-[0.12em] uppercase text-gold mb-5"><span className="block w-[3px] h-[22px] bg-gold shrink-0" />Tax year 2026</div><h1 className="font-display text-[clamp(2.25rem,5vw,3.25rem)] font-bold text-white leading-tight mb-5">Federal Income Tax <em className="not-italic text-gold">Calculator</em></h1><p className="text-[1.0625rem] text-white/65 leading-[1.75] max-w-[620px]">Estimate your U.S. federal income tax, state and local tax, and potential refund or balance due for 2026.</p></div></section>
    <section className="py-16 bg-cream"><div className="max-w-site mx-auto px-6"><FederalTaxCalculator /></div></section>
    <section className="py-16 bg-white"><div className="max-w-site mx-auto px-6"><div className="flex items-center gap-3.5 text-xs font-semibold tracking-[0.12em] uppercase text-gold mb-4"><span className="block w-[3px] h-[18px] bg-gold shrink-0" />Reference</div><h2 className="font-display text-[clamp(1.5rem,3vw,2rem)] font-bold text-navy mb-7">2026 federal income tax brackets</h2><div className="overflow-x-auto border border-border rounded-sm"><table className="w-full min-w-[720px] text-left border-collapse"><thead><tr className="bg-navy text-white"><th className="px-5 py-3.5 text-xs uppercase">Rate</th>{(Object.keys(statusLabels) as FilingStatus[]).map((status) => <th key={status} className="px-5 py-3.5 text-xs uppercase">{statusLabels[status]}</th>)}</tr></thead><tbody>{rates.map((rate, index) => <tr key={rate} className={index % 2 ? 'bg-cream' : 'bg-white'}><td className="px-5 py-3.5 text-sm font-semibold text-navy">{rate}%</td>{(Object.keys(statusLabels) as FilingStatus[]).map((status) => { const brackets = FEDERAL_TAX_RULES_2026[status].brackets; const lower = brackets[index]; const upper = brackets[index + 1]; return <td key={status} className="px-5 py-3.5 text-sm text-slate">{upper ? `${money(lower)}–${money(upper - 1)}` : `${money(lower)} and over`}</td> })}</tr>)}</tbody></table></div><p className="text-xs text-slate-light mt-4 leading-relaxed">Bracket figures and standard deductions are provided for quick reference. This calculator is an estimate and does not replace professional tax advice or an IRS filing.</p></div></section>
    <section className="py-16 bg-cream" aria-labelledby="federal-tax-guide"><div className="max-w-site mx-auto px-6 max-w-[900px]"><div className="flex items-center gap-3.5 text-xs font-semibold tracking-[0.12em] uppercase text-gold mb-4"><span className="block w-[3px] h-[18px] bg-gold shrink-0" />Tax planning guide</div><h2 id="federal-tax-guide" className="font-display text-[clamp(1.5rem,3vw,2rem)] font-bold text-navy mb-5">Federal Income Tax Calculator</h2><div className="space-y-4 text-slate leading-[1.75]"><p>Federal income tax is progressive: each portion of taxable income is taxed at the rate for its bracket. Start with gross income, subtract eligible adjustments and either the standard or itemized deduction, then apply the brackets for your filing status.</p><p>Credits reduce federal tax after it is calculated, while withholding and estimated payments affect whether you may receive a refund or owe a balance. The optional state and local figure is a simple taxable-income estimate; actual rules vary by location.</p><p>Use this estimate to plan ahead, then confirm deductions, credits, and filing requirements with current IRS guidance or a qualified tax professional.</p></div></div></section>
    <div className="bg-gold py-16"><div className="max-w-site mx-auto px-6 flex items-center justify-between gap-8 flex-wrap"><div><div className="font-display text-[clamp(1.25rem,2.5vw,1.75rem)] font-bold text-navy leading-[1.3]">Need help with your tax planning?</div><div className="text-[0.9375rem] text-navy/70 mt-2">Our advisers can help you understand your wider tax position.</div></div><Link href="/#contact" className="inline-flex items-center gap-2 bg-navy text-white px-8 py-3.5 rounded-sm font-semibold text-sm tracking-[0.05em] uppercase no-underline hover:bg-navy-light transition-colors shrink-0">Speak to a Partner ›</Link></div></div>
  </main><Footer /></>
}
