import CarLoanCalculator from '@/components/CarLoanCalculator'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Link from 'next/link'

export const metadata = {
  title: 'Car Loan Calculator | NJV Accountants',
  description: 'Estimate vehicle finance payments, total interest, and a full car loan payment schedule.',
}

export default function CarLoanCalculatorPage() {
  return <><Navbar /><main><section className="bg-navy pt-[70px]"><div className="mx-auto max-w-site px-6 py-16"><Link href="/calculators" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-gold/70 no-underline transition-colors hover:text-gold">← All Calculators</Link><div className="mb-5 flex items-center gap-3.5 text-xs font-semibold tracking-[.12em] uppercase text-gold"><span className="block h-[22px] w-[3px] shrink-0 bg-gold" />Vehicle finance tool</div><h1 className="font-display text-[clamp(2.25rem,5vw,3.25rem)] font-bold leading-tight text-white">Car Loan <em className="not-italic text-gold">Calculator</em></h1><p className="mt-5 max-w-[620px] text-[1.0625rem] leading-[1.75] text-white/65">Estimate your monthly car payment, total borrowing cost, and how each payment reduces your balance.</p></div></section><section className="bg-cream py-16"><div className="mx-auto max-w-site px-6"><CarLoanCalculator /></div></section><section className="bg-white py-16"><div className="mx-auto max-w-site px-6"><div className="max-w-3xl"><p className="text-xs font-semibold tracking-[.12em] uppercase text-gold">A practical guide</p><h2 className="mt-4 font-display text-3xl font-bold text-navy">Plan your vehicle finance with confidence</h2><p className="mt-4 leading-relaxed text-slate">Your amount financed starts with the vehicle price, then adds sales tax, fees, and any outstanding trade-in loan. Your down payment and trade-in value reduce the amount borrowed.</p><p className="mt-4 leading-relaxed text-slate">APR and loan term determine the monthly payment and total interest. A longer term can lower the monthly payment, but usually increases the interest paid. A balloon payment lowers regular payments by leaving a balance due at the end of the term.</p><p className="mt-4 leading-relaxed text-slate">This calculator is for planning purposes. Confirm rates, required fees, and final payment terms with your lender before committing to finance.</p></div></div></section><section className="bg-gold py-16"><div className="mx-auto flex max-w-site flex-wrap items-center justify-between gap-8 px-6"><div><h2 className="font-display text-2xl font-bold text-navy">Need help planning your finances?</h2><p className="mt-2 text-sm text-navy/70">Our advisers can help you make informed financial decisions.</p></div><Link href="/#contact" className="shrink-0 rounded-sm bg-navy px-8 py-3.5 text-sm font-semibold tracking-[.05em] text-white uppercase no-underline transition-colors hover:bg-navy-light">Speak to a Partner ›</Link></div></section></main><Footer /></>
}
