import type { Metadata } from 'next'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import SalaryPaycheckCalculator from '@/components/SalaryPaycheckCalculator'

export const metadata: Metadata = { title:'Salary Paycheck Calculator 2026 | NJV Accountants', description:'Estimate U.S. salary paychecks, federal withholding, FICA, Medicare, state tax, and take-home pay.' }

export default function SalaryPaycheckPage(){return <><Navbar/><main><section className="pt-[70px] bg-navy"><div className="max-w-site mx-auto px-6 py-16"><Link href="/calculators" className="inline-flex text-gold/70 text-sm font-semibold mb-8 no-underline hover:text-gold">← All Calculators</Link><div className="flex gap-3 text-xs font-semibold tracking-[.12em] uppercase text-gold mb-5"><span className="w-[3px] h-[22px] bg-gold"/>2026 estimate</div><h1 className="font-display text-[clamp(2.25rem,5vw,3.25rem)] font-bold text-white mb-5">Salary Paycheck <em className="not-italic text-gold">Calculator</em></h1><p className="text-[1.0625rem] text-white/65 leading-[1.75] max-w-[620px]">Estimate take-home pay after federal income tax, Social Security, Medicare, deductions, and your state/local tax estimate.</p></div></section><section className="py-16 bg-cream"><div className="max-w-site mx-auto px-6"><SalaryPaycheckCalculator/></div></section><section className="py-16 bg-white"><div className="max-w-site mx-auto px-6 max-w-[900px]"><h2 className="font-display text-3xl font-bold text-navy mb-5">How paycheck estimates work</h2><div className="space-y-4 text-slate leading-[1.75]"><p>This calculator annualizes your base salary, bonus, commission, and overtime, then divides the estimate by your selected pay frequency. Pre-tax deductions reduce wages before estimated taxes; post-tax deductions are applied afterward.</p><p>Federal income tax uses the current calculator tax rules and filing status. Social Security and Medicare use standard employee payroll-tax rates. State/local withholding is a rate you enter, because rules and local taxes differ widely by location.</p><p>This is a planning estimate, not a payroll statement or tax filing. Confirm withholding, benefits, and jurisdiction-specific rules with your employer or tax adviser.</p></div></div></section><div className="bg-gold py-16"><div className="max-w-site mx-auto px-6 flex items-center justify-between gap-8 flex-wrap"><div><h2 className="font-display text-2xl font-bold text-navy">Need help with payroll or tax planning?</h2><p className="text-navy/70 mt-2">Our advisers can help you understand your complete tax position.</p></div><Link href="/#contact" className="bg-navy text-white px-8 py-3.5 rounded-sm font-semibold text-sm uppercase no-underline">Speak to a Partner ›</Link></div></div></main><Footer/></>}
